const actions = {
    COMMENTS_EDIT: 'COMMENTS_EDIT',
    COMMENTS_REMOVE: 'COMMENTS_REMOVE',
    POSTS_EDIT: 'POSTS_EDIT',
    POSTS_SAVE: 'POSTS_SAVE',
    POSTS_REMOVE: 'POSTS_REMOVE',
    POSTS_VOTE: 'POSTS_VOTE'
}
